config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, :controllers => {
    :sessions => 'admin/sessions'
  }
  devise_for :customers
  scope module: :public do
    root to: 'homes#top'
    get '/about', to: 'homes#about'
    post '/homes/guest_sign_in', to: 'homes#new_guest'
    # devise_for :users を次に置き換える
    # devise_for :customers, controllers: {
    # registrations: 'custromers/registrations'
  # }
  devise_scope :customer do
    post 'customers/guest_sign_in', to: 'customers/sessions#new_guest'
  end

    resources :customers, only: [:show, :index, :update, :edit]
    resources :post_images  do
      resources :post_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
      post 'confirm', on: :collection
  end
    end
  get '/search', to: 'public/searches#search'
  get 'maps/index', to: 'maps#index'
  resources :maps, only: [:index]
  # admin側ルーティング
  namespace :admin do
    get '' => 'homes#top'
    resources :customers, only: [:show, :index, :update, :edit]
    resources :post_images
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :post_images, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  # validates :full_name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  # validates :introduction, length: {maximum: 50}

  has_one_attached :profile_image

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'no_image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit:[width, height]).processed
  end

  #def name
  #  self.last_name + self.first_name
  #end

  def self.search_for(content, method)
    if method == 'perfect'
      Customer.where(full_name: content)
    elsif method == 'forward'
      Customer.where('full_name LIKE ?', content + '%')
    elsif method == 'backward'
      Customer.where('full_name LIKE ?', '%' + content)
    else
      Customer.where('full_name LIKE ?', '%' + content + '%')
    end
  end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers = Customer.all
    @post_image = PostImage.all
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def show
    @customer =  Customer.find(params[:id])
    @post_images = @customer.post_images
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>introduction</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <%# byebug %>
    <% customers.each do |customer| %>
      <tr>
        <td><%= image_tag customer.get_profile_image, size: '50x50' %></td>
        <td><%= customer.full_name %></td>
        <td><%= customer.introduction %></td>
        <td><%= link_to 'Show', admin_customer_path(customer.id), class: "customer_#{customer.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/customers/_info.html.erb
<table class='table'>
  <tr><%= image_tag customer.get_profile_image(100,100), size:'100x100' %></tr>
  <tr>
	  <th>name</th>
	  <th><%= customer.full_name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= customer.introduction %></th>
  </tr>
</table>

<div class='row'>
  <%= link_to edit_customer_path(customer), class: "btn btn-outline-secondary btn-block edit_customer_#{customer.id}" do %>
    <i class="fas fa-user-cog"></i>
  <% end %>
</div>

app/views/admin/customers/edit.html.erb
edit

app/views/admin/customers/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
     <div class='col-md-3'>
    <h2>Customer info</h2>
    <%= render 'info', customer: current_customer %>
    <div class='col-md-8 offset-md-1'>
  
    </div>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>Customer info</h2>
      <%= render 'admin/customers/info', customer: @customer %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Post_Images</h2>
      <%= render 'admin/post_images/index',post_images: @post_images %>
      <%#= link_to 'Destroy', @post_image, method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger destroy_post_image_#{@post_image.id}"%>
    </div>
  </div>
</div>