config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, :controllers => {
    :sessions => 'admin/sessions'
  }
  devise_for :customers
  scope module: :public do
    root to: 'homes#top'
    get '/about', to: 'homes#about'
    post '/homes/guest_sign_in', to: 'homes#new_guest'
    # devise_for :users を次に置き換える
    # devise_for :customers, controllers: {
    # registrations: 'custromers/registrations'
  # }
  devise_scope :customer do
    post 'customers/guest_sign_in', to: 'customers/sessions#new_guest'
  end

    resources :customers, only: [:show, :index, :update, :edit]
    resources :post_images  do
      resources :post_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
      post 'confirm', on: :collection
  end
    end
  get '/search', to: 'public/searches#search'
  get 'maps/index', to: 'maps#index'
  resources :maps, only: [:index]
  # admin側ルーティング
  namespace :admin do
    get '' => 'homes#top'
    resources :customers, only: [:show, :index, :update, :edit]
    resources :post_images
  end
end

app/models/post_image.rb
class PostImage < ApplicationRecord
  has_one_attached :image
  belongs_to :customer
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :post_image_tag
  has_many :tags, through: :post_image_tag

  validates :couse_name,presence:true
  validates :caption,presence:true
  validates :image, presence: true

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'no_image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit:[width, height]).processed
  end

  def favorited_by?(target_customer)
    favorites.where(customer_id: target_customer.id).exists?
  end

  def self.search_for(content, method)
    if method == 'perfect'
      PostImage.where(caption: content)
    elsif method == 'forward'
      PostImage.where('caption LIKE ?', content+'%')
    elsif method == 'backward'
      PostImage.where('caption LIKE ?', '%'+content)
    else
      PostImage.where('caption LIKE ?', '%'+content+'%')
    end
  end

end

app/controllers/admin/post_images_controller.rb
class Admin::PostImagesController < ApplicationController
  def edit
    @post_image = PostImage.find(params[:id])
  end
  def destroy
    post_image = PostImage.find(params[:id])
    post_image.destroy
    redirect_to admin_customer_path(params[:customer_id])
  end
end

app/helpers/post_images_helper.rb
module PostImagesHelper
end

app/views/admin/post_images/_edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Cycling</h1>
  		<%= link_to 'Destroy', @post_image, method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger destroy_post_image_#{@post_image.id}"%>
    </div>
  </div>
</div>

app/views/admin/post_images/_index.html.erb
test
<table class='table'>
  <thead>
    <tr>
      <th>Image</th>
      <th>Name</th>
      <th>Caption</th>
      <th>Tag</th>

    </tr>
  </thead>
  <tbody>
    <% post_images.each do |post_image| %>
      <tr>
        <td><%= link_to(post_image.customer) do %>
          <%= image_tag post_image.get_image(50,50) %>
          <% end %>
        </td>
        <% if customer_signed_in? %>
        <td><%= link_to post_image.couse_name,post_image, class: "post_image_#{post_image.id}" %></td>
        <% elsif admin_signed_in? %>
        <td><%= link_to post_image.couse_name,admin_post_image_path(post_image, customer_id: post_image.customer.id), method: :delete, class: "post_image_#{post_image.id}" %></td>
        <% end %>
        <td><%= post_image.caption %></td>
        <td>コメント数: <%= post_image.post_comments.count %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/post_images/index.html.erb
  <div class='container px-5 px-sm-0'>
    <%= render 'layouts/errors', obj: @post_image %>
    <div class='row'>
      <div class='col-md-3'>
        <h2>Customer info</h2>
        <%= render 'admin/customers/info', customer: current_customer%>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Post_images</h2>
      <%= render 'admin/post_images/edit', post_images: @post_images%>
    </div>
</div>