config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, :controllers => {
    :sessions => 'admin/sessions'
  }
  devise_for :customers
  scope module: :public do
    root to: 'homes#top'
    get '/about', to: 'homes#about'
    post '/homes/guest_sign_in', to: 'homes#new_guest'
    # devise_for :users を次に置き換える
    # devise_for :customers, controllers: {
    # registrations: 'custromers/registrations'
  # }
  devise_scope :customer do
    post 'customers/guest_sign_in', to: 'customers/sessions#new_guest'
  end

    resources :customers, only: [:show, :index, :update, :edit]
    resources :post_images  do
      resources :post_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
      post 'confirm', on: :collection
  end
    end
  get '/search', to: 'public/searches#search'
  get 'maps/index', to: 'maps#index'
  resources :maps, only: [:index]
  # admin側ルーティング
  namespace :admin do
    get '' => 'homes#top'
    resources :customers, only: [:show, :index, :update, :edit]
    resources :post_images
  end
end

app/views/layouts/_footer.html.erb
<footer>
  <div class="p-3 mb-2 bg-danger text-white">
    <div class='container mt-5'>
  	  <div class='row'>
    	  <div class='mx-auto'>
    		  <p>CopyRight ©Infratop.inc</p>
    	  </div>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-light bg-danger">
    <div class="container">
      <a class="navbar-brand" href="/"><span>cycling</span></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
    <% if customer_signed_in? %>
        <div class="d-flex justify-content-center mb-2">
          <%= render 'public/searches/form' %>
        </div>
        <li>
        <%= link_to '投稿フォーム', new_post_image_path %>
        </li>
        <li class="customer-name">
            ようこそ、<%= current_customer.last_name %> さん</br>
          </li>
          <li class="ml-4">
            <%= link_to customer_path(current_customer.id),class: 'nav-link text-light' do %>
              マイページ
          <% end %>
        <li class="ml-4">
            <%= link_to destroy_customer_session_path, method: :delete,class: 'nav-link text-light' do %>
              ログアウト
            <% end %>
        </li>
       <% elsif admin_signed_in? %>
        <li class="ml-4">
            <%=  link_to admin_path,class: 'nav-link text-light' do %>
              会員一覧
            <% end %>
          </li>
           <li class="ml-4">
            <%= link_to destroy_admin_session_path, method: :delete,class: 'nav-link text-light' do %>
              ログアウト
            <% end %>
          </li>
           <% else %>
           <li class="ml-4">
            <%= link_to new_customer_registration_path,class: 'nav-link text-light' do %>
              新規登録
            <% end %>
          </li>
          <li class="ml-4">
            <%= link_to new_customer_session_path ,class: 'nav-link text-light' do %>
              ログイン
            <% end %>
          </li>
        <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cycling</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
     <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

  <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
     <%= render 'layouts/header' %>
     <main>
      <p id="notice"><%= notice %></p>
    <%= yield %>
    </main>
     <%= render 'layouts/footer' %>
  </body>
</html>